version: "3.7"


services:

#-----PROXY-----#

  nginx:
    container_name: nginx-map
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/dev.timetochange.today.conf:/etc/nginx/sites-enabled/dev.timetochange.today.conf
      - ./nginx/devtiles.timetochange.today.conf:/etc/nginx/sites-enabled/devtiles.timetochange.today.conf
      - ./nginx/map.deeptimechicago.org.conf:/etc/nginx/sites-enabled/map.deeptimechicago.org.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    restart: always
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
  
  certbot:
    container_name: certbot-map
    image: certbot/certbot
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
    restart: unless-stopped
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    depends_on:
      - nginx

# NETWORK SHOULD BE USED AS EXTERNAL NETWORK FROM OTHER DOCKER-COMPOSE FILES. 
networks:
   default:
         name: app-net